### ISSUE TITLE
Main class not found

### ISSUE THREAD

**Issue by Sandared** [jerkar/jerkar#115]
Hi,

I just compiled the current master branch and extracted the resulting zip folder into my "Jerkar HOME" directory. Then I tried to invoke Jerkar as I did before with Jerkar 0.6.0, but got the error message 
" Main class org.jerkar.tool.Main could no be found or loaded".

Any ideas?

**Comment by djeang** [comment]
Which OS are you running on ? Which JDK version ?

**Comment by djeang** [comment]
The simpler is to let build/output/distrib directory be your jerkar home.

**Comment by Sandared** [comment]
Sorry I just realized, that I added the JERKAR_HOME directory to my PATH variable and didn't add a JERKAR_HOME variable -.- Sorry for the inconvenience.
