### ISSUE TITLE
IntellijJ integration

### ISSUE THREAD

**Issue by patricksan** [jerkar/jerkar#13]
The modules today are extremely tied with Eclipse. IntelliJ is getting a lot of attention. It deserves to have a look.

**Comment by djeang** [comment]
Hi patrick. Nice to see you here :-)
Indeed, Jerkar was developed using Eclipse only. I need definitivly to have a look on Intellj (which i have almost never used).
I will try to build Jerkar within IntelliJ to see how it is challenging and maybe include an intellij plugin for Jerkar soon (Sure an Jerkar plugin for IntelliJ would be nice as well).

**Comment by patricksan** [comment]
I would focus and make the plugin a plus, not the main drive. Because we
can easily execute a terminal command in both tool what would build the
project.

On Thu, May 28, 2015 at 11:45 PM, Jerome Angibaud <notifications@github.com>
wrote:

> Hi patrick. Nice to see you here :-)
> Indeed, Jerkar was developed using Eclipse only. I need definitivly to
> have a look on Intellj (which i have almost never used).
> I will try to build Jerkar within IntelliJ to see how it is challenging
> and maybe include an intellij plugin for Jerkar soon (Sure an Jerkar plugin
> for IntelliJ would be nice as well).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jerkar/jerkar/issues/13#issuecomment-106609049>.
>



-- 
*Patrick Santana*
General Manager


MOOGU
Maalderijstraat 13-15
B-9255 Buggenhout


Tel. : +32 52 810 010
Tel. direct : +32 496 53 56 70
e-mail: psantana@moogu.com


http://www.moogu.com
