### ISSUE TITLE
Remove plugins to a separated repository

### ISSUE THREAD

**Issue by patricksan** [jerkar/jerkar#14]
The whole idea is much more than just a plugin for eclipse. Considere to remove the core to a main repository. Like maven has it own code and around it plugins.

**Comment by djeang** [comment]
The idea is to ship Jerkar with most usefull plugins out-of -the-box. Beside, plugins considered as less essiential should be developped in their own repository indeed.

So for example, I included the Eclipse plugin cause I find it essential (I am an Eclipse user). I think it would make sense to integrate a plugin for IntelliJ as well (for generating or reading Intellij metadata).

**Comment by patricksan** [comment]
I understand your point, but it makes more difficult to have it running in
Jenkins, eg. I got that it is essential for you as a Eclipse user, but
sounds limit the amount of people can use it.

**Comment by djeang** [comment]
Sorry Patrick, i was unclear, the Eclipse plugin shipped with Jerkar (referenced in #7) is in fact an Eclipse Plugin for Jerkar (not the opposite). IOW it is **not** something that you plug in your IDE to enrich it.  This one is just classes that : 
* allow Jerkar to deduce the build classpath by reading .classpath Eclipse XML file
* can configure an eclipse project by generating .classpath and .project from the dependencies declared in the Jerkar build file (as mvn eclipse:eclipse does).
This plugin is not active by default, there is no adherence to any 3rd party lib/API and Jerkar can work absolutly without it. So no problem with Jenkins or command line users.

Beside, I would like to see a Jerkar plugin for Eclipse (developed in its own repo of course).

**Comment by patricksan** [comment]
Gotcha you!
