### ISSUE TITLE
Consider configure the project for IntelliJ also

### ISSUE THREAD

**Issue by patricksan** [jerkar/jerkar#15]
Mainly it is hard to develop on IntelliJ. It creates a lot of projects:
![screen shot 2015-05-28 at 20 53 09](https://cloud.githubusercontent.com/assets/81615/7868342/a6271af6-057b-11e5-98a8-6659c822e936.png)

There is a free version of IntelliJ.

**Comment by djeang** [comment]
Think it is related to #13

**Comment by patricksan** [comment]
Not that related. #13 is about the plugin itself. This one is about have the github project also configured for contributors on IntelliJ.

**Comment by djeang** [comment]
What is consisting in ? Just commit some metadata files as .classpath and .project for eclipse ?

**Comment by patricksan** [comment]
normally we never commit the intellij files, as it can ready maven and all
others tools.
But in your case, I would commit the .idea folder.

**Comment by djeang** [comment]
That's good sense :-) You're newly granted to commit. Fell free to do it.

**Comment by djeang** [comment]
Done.
The project definition (.idea folder) lies in "distrib-all" module.

![capture](https://cloud.githubusercontent.com/assets/4290762/9931152/6d1198ac-5d39-11e5-9779-c3d1673e2fcd.PNG)
