### ISSUE TITLE
No way to filter dependencies for fat jars?

### ISSUE THREAD

**Issue by cuchaz** [jerkar/jerkar#36]
When merging dependency jar files together to make a fat jar, sometimes we need to filter out files from the dependency jars or the fat jar will not work as intended. For example, signature files need to be removed or the fat jar could throw and exception:

`java.lang.SecurityException: Invalid signature file digest for Manifest main attributes`

I couldn't find a simple way in jakar to filter files from fat jars, but this workaround worked for my project. Basically, I open the fat jar as a zip file and delete anything I don't want.

```
	@Override
	protected JkJavaPacker createPacker() {
		return JkJavaPacker.builder(this)
			.doFatJar(true)
			.extraAction(new JkExtraPacking() {
				
				private String[] filteredExtensions = { "RSA", "DSA", "SF" };
				
				@Override
				public void process(JkJavaBuild build) {
					
					// move the fat jar to a temp file
					JkJavaPacker packer = JkJavaPacker.of(Build.this);
					File tempFile = build.ouputDir("temp.jar");
					packer.fatJarFile().renameTo(tempFile);
					
					// make a new fat jar with the stuff we want to keep
					try (ZipFile zipIn = new ZipFile(tempFile)) {
						try (ZipOutputStream zipOut = JkUtilsZip.createZipOutputStream(packer.fatJarFile(), Deflater.DEFAULT_COMPRESSION)) {
							Enumeration<? extends ZipEntry> entries = zipIn.entries();
							while (entries.hasMoreElements()) {
								ZipEntry entry = entries.nextElement();
								if (shouldSkip(entry)) {
									continue;
								}
								copy(zipIn, entry, zipOut);
							}
						}
					} catch (IOException ex) {
						throw new RuntimeException(ex);
					}
				
					// cleanup
					tempFile.delete();
				}

				private boolean shouldSkip(ZipEntry entry) {
					
					// skip directories
					if (entry.isDirectory()) {
						return true;
					}
					
					// skip things that break the jar
					for (String filteredExtension : filteredExtensions) {
						if (entry.getName().endsWith("." + filteredExtension)) {
							return true;
						}
					}
					
					return false;
				}
				
				private void copy(ZipFile zipIn, ZipEntry entry, ZipOutputStream out) {
					try {
						
						// start the entry
						out.putNextEntry(entry);
						
						// copy the data
						InputStream entryIn = zipIn.getInputStream(entry);
						final int bufSize = 2048;
						final BufferedInputStream buf = new BufferedInputStream(entryIn, bufSize);
						int count;
						final byte data[] = new byte[bufSize];
						while ((count = buf.read(data, 0, bufSize)) != -1) {
							out.write(data, 0, count);
						}
						buf.close();
						entryIn.close();
						
						// finish the entry
						out.closeEntry();
						
					} catch (final IOException e) {
						throw new RuntimeException(e);
					}
				}
			})
			.build();
	}
```

Maybe there could be a way to simplify the build process to make this kind of thing easier to do in the future?

Thanks for making such a great build system btw. I really like it so far. =)

**Comment by djeang** [comment]
Adding a JkJavaPacker.Builder#fatJarFilter(JKPathFilter) method seems cleanest  solution. 
@cuchaz Does it match your expectation ?

**Comment by cuchaz** [comment]
Ideally, the best way to do this is to filter out unwanted files while jerkar is merging each jar file. If fatJarFilter() does that, then great. But removing the unwanted files by re-creating the entire far jar (like my workaround does) works too.

**Comment by djeang** [comment]
Indeed, filering at merging time is better. 
Also I think excluding META-INF/*.SF, META-INF/*.DSA, META-INF/*.RSA for fat jar by default makes sense.

**Comment by djeang** [comment]
Now, these 3 patterns has been filtered out from the fat jar by default.

**Comment by cuchaz** [comment]
I think the filtering is not working for merged jars?

[A quick scan of the source shows the zip merger doesn't use the filter?](https://github.com/jerkar/jerkar/blob/master/org.jerkar.core/src/main/java/org/jerkar/api/file/JkZipper.java#L205)

**Comment by cuchaz** [comment]
I'm reopening this issue to make sure it's not forgotten. I think the issue is not quite fixed yet. See above comment.

**Comment by djeang** [comment]
Added filtering on merged jars. Can you confirm that's ok for you now ?

**Comment by cuchaz** [comment]
Yup! Works great. =)
