### ISSUE TITLE
Feature request: make a fat jar, but allow not calling it "fat"

### ISSUE THREAD

**Issue by cuchaz** [jerkar/jerkar#38]
In some of my projects, the only jar artifact is a fat jar that gets distributed directly to end users. I'd prefer to not tell users my jar is "fat". They don't really care about those kinds of details.

Here's a quick workaround that fixes the issue for me, but maybe some jerkar users would enjoy a simpler solution:
```
@Override
protected JkJavaPacker createPacker() {
	return JkJavaPacker.builder(this)
		.includeVersion(true)
		.doJar(false)
		.doSources(false)
		.doFatJar(true)
		.extraAction(new JkExtraPacking() {
			
			@Override
			public void process(JkJavaBuild build) {
				
				// rename the fat jar to the regular jar
				JkJavaPacker packer = createPacker();
				packer.fatJarFile().renameTo(packer.jarFile());
			}
		})
		.build();
}
```

One suggestion might be to allow the `JkJavaBuild.JkOptionPack.fatJarSuffix` to allow a null value. The null value here could signify that the "-fat" in the jar name should be omitted. Although, if `JkJavaPacker.doJar(true)`, then maybe jerkar should warn about the naming conflict.

Thanks!

**Comment by djeang** [comment]
Yep. Nice suggestion.

**Comment by djeang** [comment]
Now, if you add it to your build class, the fat jar name will have no suffix.
{
        this.pack.fatJar = true;
        this.pack.fatJarSuffix = null;
}

**Comment by cuchaz** [comment]
This works great! thanks! =)
