### ISSUE TITLE
Proguard integration? Or maybe usage example for java-based build tools

### ISSUE THREAD

**Issue by cuchaz** [jerkar/jerkar#39]
[Proguard](http://proguard.sourceforge.net/) is a popular minifier for Java. While specific integration between Proguard and jerkar would be nice, maybe tight integration with specific third-party tools isn't a goal for jerkar.

At the very least, maybe jerkar users would benefit from an example of how to use java-based third-party tools like Proguard. Since Proguard is java-based, using jerkar's dependency management tools is a really elegant way to "install" Proguard and use it in a project. Here's the code I'm using:

```
@Override
protected JkJavaPacker createPacker() {
	return JkJavaPacker.builder(this)
		.extraAction(new JkExtraPacking() {
			
			@Override
			public void process(JkJavaBuild build) {

				// get the proguard jar
				JkVersionedModule proguardMod = JkModuleId.of("net.sf.proguard", "proguard-base").version("5.1");
				JkDependencies proguardDeps = JkDependencies.builder()
					.on(proguardMod.moduleId(), proguardMod.version().name()).scope(COMPILE)
					.build();
				JkResolveResult resolved = dependencyResolver().withDependencies(proguardDeps).resolve(COMPILE);
				File proguardJar = resolved.filesOf(proguardMod.moduleId()).get(0);
				
				// move the fat jar to a temp file
				JkJavaPacker packer = createPacker();
				File tempFile = build.ouputDir("temp.jar");
				packer.fatJarFile().renameTo(tempFile);
				
				// run proguard
				JkProcess.of("java")
					.andParameters("-jar", proguardJar.getAbsolutePath())
					.andParameters("@proguard.conf")
					.andParameters("-injars", tempFile.getAbsolutePath())
					.andParameters("-outjars", packer.fatJarFile().getAbsolutePath())
					.failOnError(true)
					.runSync();
			
				// cleanup
				tempFile.delete();
			}
		})
		.build();
}
```

Maybe the docs could include an example like this? This code probably isn't robust enough to cover all the possible use cases, but maybe it's helpful to some. Feel free to modify it and make it better.

**Comment by djeang** [comment]
I am impressed how fast you get it to deal with Jerkar :-) 
To ease the usage of Proguard, I would put it in a separate plugin that add this extra action to the default JkJavaPacker. 
In meantime, this how you can achieve it in a more elegant way.
```
@JkImport("net.sf.proguard:proguard-base:5.1")
class Build extends JkJavaBuild {    
    
    @Override
    protected JkJavaPacker createPacker() {
        return JkJavaPacker.builder(this)
                .extraAction(new JkExtraPacking() {
                        
                        @Override
                        public void process(JkJavaBuild build) {
                                
                                // move the fat jar to a temp file
                                JkJavaPacker packer = createPacker();
                                File tempFile = build.ouputDir("temp.jar");
                                packer.fatJarFile().renameTo(tempFile);
                                
                                // run proguard
                                proguard.ProGuard.main(new String[] {"@proguard.conf", "-injars", tempFile.getAbsolutePath(),
                                        "-outjars", packer.fatJarFile().getAbsolutePath()});
                                    
                                // cleanup
                                tempFile.delete();
                        }
                })
                .build();
    }
...
```
 This way, proguard is automatically added to the build classpath (don't forget to update your eclipse .classpath file by running `jerkar eclipse#generateFiles`) right after adding the `@JkImport`annotation.

**Comment by cuchaz** [comment]
Oooh, that's clever. jerkar is full of surprises! That works great, thanks! =)

One caveat of your approach is the implications for licensing. Directly "linking" to proguard (rather than executing the jar) requires the build script be GPL compatible, should it ever be distributed. Proguard actually writes a console message about this:
```
ProGuard, version 5.1
ProGuard is released under the GNU General Public License. You therefore
must ensure that programs that link to it (org.jerkar.tool, cuchaz.launcher, org.jerkar.api.utils, ...)
carry the GNU General Public License as well. Alternatively, you can
apply for an exception with the author of ProGuard.
```

It's probably not a big deal, but it might be possible for an open-source, but not GPL-compatible, project that's using jerkar and Proguard in this way to be in violation of the Proguard license.

**Comment by cuchaz** [comment]
Actually, I lied. Proguard's main() has System.exit()s in it. We'd have to call something other than main(). Like this:
```
try {
	proguard.Configuration configuration = new proguard.Configuration();
	proguard.ConfigurationParser parser = new proguard.ConfigurationParser(new String[] {
		"@proguard.conf",
		"-injars", tempFile.getAbsolutePath(),
		"-outjars", packer.fatJarFile().getAbsolutePath()
	}, System.getProperties());
	parser.parse(configuration);
	parser.close();
	new proguard.ProGuard(configuration).execute();
} catch (IOException | proguard.ParseException ex) {
	throw new RuntimeException(ex);
}
```

**Comment by djeang** [comment]
Mmmm... Your right, direct API call may lead in License issue...
So maybe i would bundle a jerkar plugin that download the Proguard jar and then execute it. I can also apply for an exception with the authors.

In meantime this is a shortcut to download any jar from repository
```
File proguardJar = this.downloadRepositories().get(JkModuleDependency.of("net.sf.proguard", "proguard-base", "5.1"));
```

**Comment by djeang** [comment]
I've added some methods to ease usage of external Java tools. Now you can achieve it using 
```
    @Override
    public void doPack() {
        super.doPack();
        File tempFile = ouputDir("temp.jar");
        this.packer().fatJarFile().renameTo(tempFile);
        File proguardJar = this.buildRepos().get("net.sf.proguard", "proguard-base", "5.1");
        JkJavaProcess.of().runJarSync(proguardJar, "@proguard.conf", "-injars", tempFile.getAbsolutePath(),
                "-outjars", packer().fatJarFile().getAbsolutePath());
        tempFile.delete();
    }
```

**Comment by cuchaz** [comment]
Oooh, that looks great! I'll have to set up a from-source build of jerkar so I can try the new features. =)

**Comment by djeang** [comment]
No you don't need to.  You can grab the latest snapshot from here : http://project.jerkar.org/binaries/jerkar-distrib.zip 
This link is displayed here http://project.jerkar.org/download.html .

**Comment by cuchaz** [comment]
Ah, too late. Oh well. Building from source is pretty easy though. Nice job!

Found some problems though. I'll make separate issues.

**Comment by cuchaz** [comment]
The new java tools integration works great! Thanks!
