### ISSUE TITLE
Dependency classpath order

### ISSUE THREAD

**Issue by cuchaz** [jerkar/jerkar#40]
Sometimes libraries provide implementations of the same classes, and which one gets loaded at runtime is determined by the classloader rules, which are based mainly on classpath order. Meaning, in order to get the dependencies loaded correctly, we need to be able to specify the classpath order for all the dependencies. So that library A correctly overrides library B by having an earlier classpath order, etc.

In eclipse, you can adjust the library order easily with the "up" and "down" buttons. Sadly, manual adjustments are overrwritten the next time jerkar is used to write the classpath. In the build script, the JkDependencies.Builder explicitly defines an order for dependencies (using the .on() chain), but the dependencies in the classpath appear to be sorted by type and name?

Is there a way to get the classpath builder to use an explicit order for dependencies so that class overrides are handled correctly?

I can use the "up" and "down" buttons after the classpath is generated, but that workaround is tedious.

Thanks!

**Comment by djeang** [comment]
I understand. Indeed, it's intuitive that the classpath order should follow the declaration chain order. I think it's a priority to fix as I don't see reasonable workaround.
