### ISSUE TITLE
eclipse classpath builder adds wrong source folders

### ISSUE THREAD

**Issue by cuchaz** [jerkar/jerkar#41]
If my build script has these overrides on the JkJavaBuild template:

```
@Override
public JkFileTreeSet editedSources() {
	return JkFileTreeSet.of(file("src"));
}

@Override
public JkFileTreeSet editedResources() {
	return super.editedResources()
		.and(baseDir().andFilter(JkPathFilter.include("LICENSE.txt")));
}
```

Then the eclipse classpath has "." and "./src" as source folders, but only "src" should be the source folder. "." should not be a source folder.

I'm using jerkar compiled from commit a9faab6a3cd09c0e1e48a2371629f325d5fbc478

I'm guessing this could be tricky to fix... because resource folders generally should be on the classpath. Except, I'm using the resource system to include LICENSE.txt in the jar file like you suggested, even though LICENSE.txt isn't really a resource and it doesn't need to be on the classpath.

Maybe we need a mechanism to include non-classpath files in Jars that is separate from the resource mechanism? Or teach the resource mechanism to not create source folders for file resources?

**Comment by djeang** [comment]
If you want these files not been included in the Eclipse build path than this mean that it should not be considered as resources.
There is 2 points 

- there is a bug cause normally Jerkar should include "." in Eclipse buildpath but with inclusion of "License.txt" so only this file is in the buildpath, not the whole project.

-  You're right, a method like JkJavaPacker#withExtraFilesInJar(JkFileTree) is more appropriate to include files that only need to be there at jar creation time.   If you want to implement that you're more than welcome.

**Comment by cuchaz** [comment]
Ok, I'll send a PR with a `withExtraFilesInJar()` feature. Thanks for your help!
