### ISSUE TITLE
two different ways to configure packers

### ISSUE THREAD

**Issue by cuchaz** [jerkar/jerkar#42]
It looks like there are two different ways to configure `JkJavaPacker` that offer different functionalities. The two ways overlap in a lot of key features, but there are significant differences.

The `JkJavaBuild.JkOptionPack` method allows configuration of `doFatJar` and `farJarSuffix`, but not `fatJarEntryFilter` or other things like `doJar` `doSources`, etc.

The `JkJavaPacker.Builder` method allows configuration of `doFatJar`, `farJarEntryFilter`, and others like `doJar`, `doSources`, but not `fatJarSuffix`.

To fully configure the java packer, one must use both methods, which can conflict over options like `doFatJar`.

Here's an example:
```
public class Build extends JkJavaBuild {

	public Build() {
		pack.fatJarSuffix = null;
	}
	
	@Override
	protected JkJavaPacker createPacker() {
		return JkJavaPacker.builder(this)
			.includeVersion(true)
			.doJar(false)
			.doSources(false)
			.doFatJar(true)
			.build();
	}
}
```

This is pretty confusing. Maybe we could have a unified configuration system? Or ensure that both configuration systems offer the same functionality without conflicting?

**Comment by djeang** [comment]
The idea is that `JkJavaBuild.JkOptionPack`  holds common options about packaging ( see [options section 3.3](http://project.jerkar.org/documentation/latest/reference.html) ).
This restricts the types you can pass (basically boolean, number, string, file) but add ability to autodoc and inject values from the command line. 
So not every parameter is relevant to be passed as an option. For example you may sometime generate the javadoc, sign with pgp, ...or not.
To be honnest, may I put to much there (i.e : fatJarSuffix is not likely to vary from build to build).

On the other side `createPacker` is more powerfull as it allows to pass JkFilePath or JkExtraPacking and override the default settings configured from options.

If I had to wipe one, I would keep `createPacker` which is more powerfull but we would loose the power to inject parameters at build time.

Maybe I should remove some stuff in JkOptionPack and document better `createPacker` to reduce confusion. 
I think fatJarSuffix may be remove from JkPackOption. What do you think of ?
Do you have an other design in mind ?

**Comment by cuchaz** [comment]
If `JkOptionPack` is meant to be a simpler and easier-to-use way to configure packers than `JkJavaPacker.Builder`, then I think that's perfectly fine. Just make sure `JkOptionPack` offers a true subset of the features in `JkJavaPacker.Builder`. Meaning, `JkJavaPacker.Builder` should be able to do everything `JkOptionPack` can do, and it should ignore/override any configuration from `JkOptionPack`.

Maybe the simplest fix for this is to improve `JkJavaPacker.Builder` to handle the `fatJarSuffix` and make sure `JkJavaPacker.Builder` doesn't construct a packer that looks for config from any `JkOptionPack`. Or allow `JkJavaPacker.Builder` to pull config from a `JkOptionPack` with a non-default flag.

We can reduce confusion by updating the docs to say something like: `JkOptionPack` should be the first thing a user should try because it's easier to use. If a user needs more flexibility/power, then 'upgrade' to `JkJavaPacker.Builder`.

**Comment by djeang** [comment]
:+1:
I have just commited for adding missing method to the builder... and few improved javadoc.
The idea is that builder always override default/options.
