### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by djeang** [jerkar/jerkar#55]
Hi Jeff. Thanks for the quite valuable job you did for Jerkar so far. 
Do not hesitate to suggest some improvement about the tool you feel relevant. I'll do my best to make it.
Btw, how do you use Jerkar ? Command line ? Eclipse GUI plugin ? Launching main methods within Eclipse ?

**Comment by cuchaz** [comment]
No problem! =)

I use a combination of command line and the Eclipse GUI plugin.
