### ISSUE TITLE
eclipse#generateFiles in embedded mode relies on classpath variables that don't exist

### ISSUE THREAD

**Issue by cuchaz** [jerkar/jerkar#64]
When Jerkar is installed normally and the classpath variables in Eclipse are defined, `eclipse#generateFiles` works fine.

But when Jerkar is being used in embedded mode, `eclipse#generateFiles` still references classpath variables `JERKAR_HOME` and `JERKAR_REPO` which don't exist because Jerkar isn't really installed. Since there's no install directory, we couldn't set `JERKAR_HOME` even if we wanted to.

Maybe we can add an option to always use absolute paths in the `.classpath` file? And then turn on that option by default when Jerkar is in embedded mode?

Honestly though, I'd prefer to get rid of the classpath variables entirely. Unless we go to [extraodinary](https://bitbucket.org/cuchaz/jfxgl-env/src/68cde3482711bb2a495f566a27429cd1481601b2/build/def/Build.java?at=default&fileviewer=file-view-default#Build.java-138) [lengths](https://bitbucket.org/cuchaz/jfxgl-env/src/68cde3482711bb2a495f566a27429cd1481601b2/build/ant/cuchaz/jfxgl/SetClasspathVarTask.java?at=default&fileviewer=file-view-default) to automate setting the classpath variables, it has to be done manually in the Eclipse GUI. That's just another friction point for new users of Jerkar. It seems like an unnecessary step when it would be pretty simple to just use absolute paths instead. There's really no harm in using absolute paths in the `.classpath` file anyway, since typically that file is not included in source control.

**Comment by djeang** [comment]
Thanks for this patch.
Personnaly I like to have `.classpath` in source control as it make projects work out of the box. But good to have options.

Anyway there is a problem withcembedded mode. `.classplath` should be generated without mentioning `JERKAR_HOME` but relative path.

Concerning `JERKAR_REPO` , Eclipse plugin can help to set this variable by default.
