### ISSUE TITLE
IntelliJ IDEA plugin to generate .iml files

### ISSUE THREAD

**Issue by cuchaz** [jerkar/jerkar#72]
I need to start supporting IntelliJ IDEA users for some of my projects, so I'm going to look into teaching Jerkar how to write the .iml files.

I see there's already a [plugin project started](https://github.com/jerkar/ideaPlugin4Jerkar), so I can hopefully build onto that.

**Comment by cuchaz** [comment]
Actually... [Gradle is actively working on supporting the Kotlin language for build scripts.](https://github.com/gradle/kotlin-dsl/releases) Since groovy is the main reason I hate Gradle, working in Kotlin might be enough to entice me to go back to Gradle as my build tool of choice. Kotlin is such a wonderful language, so I have high hopes.

I'll leave this issue open until I figure out what I'm doing though.

**Comment by cuchaz** [comment]
I've spent some time using the new Gradle+Kotlin tool. It's certainly a vast improvement over what I remember the old Groovy version to be. The cross-IDE support is excellent as well. Gradle is actually usable for build script writers now! =)

Anyway, I think I'm going to go back to Gradle as my JVM build tool of choice, so I'll just close this issue.

**Comment by djeang** [comment]
I am currently working to improve IntelliJ support, and specially the .iml generation. It does work for now if you execute 'jerkar idea#generateIml'.

I don't plan for now to support Kotlin as the main philosophy of Jerkar is to build using the same language that the code you build.

Isn't there a native build tool for Kotlin ?

**Comment by djeang** [comment]
May Kobalt http://beust.com/kobalt/home/index.html be a tool of choice... look similar to jerkar... but for Kotlin :-)

**Comment by cuchaz** [comment]
Yeah, I've been using Kobalt for some projects. It's ok. The IDE integration isn't great though. And it's a bit slow to use.

I'm starting to think Gradle+Kotlin is much better than Kobalt though. The more I use Gradle+Kotlin, the more I like it. The fact that it has high adoption and great IDE integration is really attractive. I also think it would make future contributors more likely to contribute if I can stick to tools they probably already know.

Kotlin scripting isn't necessarily a requirement for me though. Honestly, I'd be happy with any language that is amenable to static analysis so that it has strong IDE support. Groovy was just terrible at that. Java is great for that of course, but I think Gradle didn't adopt it because the language is too verbose. Too bad. Kotlin seems like a really good fit though.

Honestly, I think Kotlin will eventually replace Java as the main JVM language for new projects. If not Kotlin, then maybe Ceylon. Statically-typed JVM languages are really getting good now.

I just love Jerkar though, so I'm sad to switch. But now that Gradle isn't tied to a terrible language, I think the higher adoption and excellent IDE support make it the better choice for now.

**Comment by djeang** [comment]
That's fine. Anyway thank you for the contribution you made to Jerkar : it has really helped !

One question : If you use Groovy with Kotlin DSL, does it mean that you have swithed from Eclipse to IntelliJ ? Is there descent tooling for this combination in Eclipse ?

By the way, I have already started to write a graphical jerkar plugin for Intellij, similar to what exists for Maven and gradle. Hope you'll have a look whenit will be ready (just for curiousness). :-)

**Comment by cuchaz** [comment]
That's weird. My comment didn't save. Let's try again.

For some projects, I use Eclipse, and for other projects, I use IntelliJ. It depends on what languages I'm using, really. IntelliJ is much better for Kotlin for instance.

Also, good luck with the IntelliJ plugin. I'll try it out when you're done. =)
